from pathlib import Path
import json
series = [
 ('signal','失物电波','电子',[
 ('口袋收音机','a chunky orange pocket radio with one large blue tuning dial',2,1),('软盘盒','a single turquoise floppy disk',1,1),('老式呼机','a small purple pager with simple green screen',1,1),('胶片相机','a cream and red retro camera with one big dark lens',2,2),('薄荷游戏机','a mint handheld game console with two chunky buttons',1,2),('磁带随身听','a yellow cassette walkman with visible cassette window',2,1),('猫耳耳机','pink cat-ear over-ear headphones',2,2),('小电视','a squat blue CRT television with two short antennae',2,2),('打字机','a simple red retro typewriter with a single blank page',2,2),('星际寻呼仪','a cyan space communicator with an oversized orange antenna',1,2),('透明掌机','a purple translucent handheld console with simple visible big shapes',1,2),('零号终端','an iconic white cube computer with a single glowing orange eye',2,2)]),
 ('playroom','童年放映室','玩具',[
 ('黄色小鸭','a simple yellow rubber duck with orange beak',1,1),('悠悠球','a chunky red yo-yo with short curled white string',1,1),('积木小屋','a tiny colorful block house with red triangular roof',2,2),('发条机器人','a cute cream toy robot with orange head antenna and wind-up key',1,2),('纸箱恐龙','a green blocky toy dinosaur',2,2),('星星陀螺','a blue spinning top with a yellow star on top',1,1),('宇航熊','a chubby teddy bear wearing a simple white space helmet',1,2),('街机迷你柜','a purple miniature arcade cabinet with cyan screen',1,2),('鲸鱼水枪','a blue cartoon whale-shaped water pistol',2,1),('纸月木马','a cream rocking horse with crescent shaped red rockers',2,2),('机械企鹅','a toy penguin with orange wind-up key and blue goggles',1,2),('彩虹独角兽','a white toy unicorn with a chunky pastel rainbow mane',2,2)]),
 ('encore','午夜安可','音乐',[
 ('橙心唱片','a single black vinyl record with large orange center',2,2),('樱桃沙锤','a red maraca with simple cream zigzag',1,2),('口袋口琴','a chunky cyan silver harmonica',2,1),('小号节拍器','a brown triangular metronome with oversized orange pendulum',1,2),('薄荷麦克风','a mint vintage microphone on a short stand',1,2),('落日吉他','a small stylized orange acoustic guitar with only four thick strings',1,2),('紫色合成器','a small purple synthesizer keyboard with few big keys',2,1),('云朵八音盒','a cream music box with an open lid and one blue cloud ornament',2,2),('霓虹鼓机','a blue square drum machine with four large neon pink pads',2,2),('星轨留声机','a navy gramophone with a big golden horn',2,2),('月光小提琴','a simplified violet violin with a white crescent motif',1,2),('天使竖琴','a small gold harp with white wing-shaped frame and five thick strings',1,2)]),
 ('atelier','手作小宇宙','工艺',[
 ('釉白茶杯','a squat cream teacup with a blue stripe',1,1),('风铃','a simple round blue glass wind chime with red hanging strip',1,2),('纸鹤','a single orange origami crane with large folded planes',2,1),('青瓷花瓶','a simple pale green ceramic vase with one white blossom silhouette',1,2),('橘猫陶偶','a round orange ceramic cat sitting upright',1,1),('彩窗灯','a small geometric stained glass lamp with five big colored panels',1,2),('雪山水晶球','a clear snow globe containing one simple blue mountain',2,2),('狐面','a white fox mask with bold red accents',1,2),('锦鲤摆件','a curved red-white koi sculpture on a small blue wave',2,1),('金线折扇','a navy folded-open fan with three broad gold rays',2,1),('琉璃莲花','a stylized turquoise lotus sculpture with six large petals',2,2),('日冕陶盘','a gold and orange sun face ceremonial plate with bold radial shapes',2,2)]),
 ('roadtrip','城市漫游','模型',[
 ('红色滑板','a short red skateboard with chunky cyan wheels',2,1),('黄色出租车','a tiny yellow taxi toy car in three-quarter view',2,1),('双层巴士','a small red double decker bus model with six large blue windows',2,1),('奶油摩托','a cream and turquoise scooter model with orange seat',2,2),('复古跑车','a compact red sports car model with bold white stripe',2,1),('蓝色电车','a short blue tram model with one simple roof connector',2,1),('直升机模型','a toy orange helicopter with two broad rotor blades',2,2),('月面越野车','a white lunar rover toy with four oversized blue wheels',2,2),('瓶中帆船','a clear round bottle containing one orange sailboat',2,1),('极光飞船','a sleek purple toy spaceship with wide cyan wings',2,1),('深海潜艇','a yellow round submarine model with two large blue portholes',2,1),('星穹列车','a magical navy locomotive toy with golden crescent chimney',2,2)]),
 ('pantry','甜蜜补给站','食玩',[
 ('草莓汽水','a squat pink soda bottle with one large strawberry emblem and no words',1,2),('桃子果酱','a small glass jam jar with pink gingham lid and peach icon',1,1),('云朵棉花糖','a large pale blue cotton candy puff on a short pink stick',1,2),('猫爪饼干罐','a cream cookie tin shaped like a cat paw with orange paw pads',2,2),('柠檬糖盒','a yellow lemon shaped candy tin',2,1),('熊猫便当','a mint bento box containing one simple panda rice ball',2,1),('樱花茶罐','a pink cylindrical tea tin with one large white flower and no text',1,2),('星空棒棒糖','a large purple star shaped lollipop with pale blue swirl',1,2),('月兔月饼盒','a round navy gift tin with a gold rabbit emblem',2,2),('水晶蜜罐','a large amber honey jar with angular glass and wooden dipper',1,2),('彩虹蛋糕','a cake slice with three broad rainbow layers and a cherry',2,2),('金箔可可杯','a whimsical golden goblet of hot cocoa with one star marshmallow',1,2)]),
 ('archive','旧城记忆','古物',[
 ('邮差皮包','a small brown satchel with a large orange clasp',2,2),('铜钥匙','a chunky brass skeleton key with circular head',1,2),('旧街路牌','a small teal arrow shaped street sign with blank white stripe no text',2,1),('黄铜怀表','a simple brass pocket watch with ivory face and thick black hands no numerals',1,1),('旅行皮箱','a chunky brown leather suitcase with two broad cream straps',2,2),('煤油提灯','a blue vintage lantern with an orange glass light',1,2),('折叠望远镜','a chunky brass telescope with blue grip',2,1),('航海罗盘','an open red brass compass with one large four-point star',1,1),('珐琅胸针','a blue swallow bird enamel brooch with gold edge',2,1),('机械座钟','a small cream mantel clock with two bold orange pillars',2,2),('珊瑚王冠','a simple gold crown with three large coral red gems',2,1),('初代城徽','a navy gold shield medallion with a single sun and wave emblem',1,2)]),
 ('anomaly','异常观察局','奇物',[
 ('微光蘑菇','a single cyan mushroom with a purple stalk and three pale spots',1,1),('瓶装雨云','a squat glass jar containing one dark blue rain cloud',1,1),('困困石头','a smooth purple pebble with two closed sleepy eyes',1,1),('漂浮茶壶','a round teal teapot with one tiny cream orbiting cup',2,2),('倒转沙漏','a chunky orange hourglass with purple sand flowing upward',1,2),('发芽磁铁','a red horseshoe magnet with one green leaf sprouting from it',1,2),('星屑水晶','a purple geometric crystal with three large faces and one orange star inside',1,2),('月亮标本','a cream crescent moon inside a simple navy glass dome',2,2),('口袋黑洞','a small dark navy orb surrounded by a single orange ring',2,2),('方糖宇宙','a transparent cyan cube containing a tiny violet planet with a simple ring',1,1),('时间胶囊','a white orange capsule with one giant blue lens at center',1,2),('迷你日蚀','a black sun orb with a bold orange corona held by a simple gold crescent stand',2,2)])
]
base='''Production sprite sheet for a 2D cartoon cel-shaded collecting game. EXACTLY 12 separate object icons arranged in a precise 4-column by 3-row evenly spaced grid. Each object is centered in its own equal 384x341 cell, takes at most 72 percent of cell width and height, fully contained with wide empty gutters. NO visible grid. Transparent alpha background, absolutely NO scenery, background, floor, pedestal, cast shadow, checkerboard, labels, words, letters, captions, watermarks or UI.
ART DIRECTION: bold clean hand-drawn anime cel-shaded inventory icons, simple playful chunky silhouettes. Thick dark navy outer contour, very few interior lines. Only 3 to 5 flat color areas per object, TWO-TONE hard-edged cel shadows and at most one broad highlight. Slight 3/4 view, charming stylized proportions. Readable at 48 pixels. Think polished vector-like cartoon stickers, not realistic illustrations. No realistic metal, glass refraction, texture, wear, grain, scratches, tiny buttons, detailed strings, micro-details, photorealism, 3D render, gradients or painterly lighting. Colored silhouettes must dominate. Every item equally important, consistent line width. Do not connect any items or add decorative effects between cells.
Exact left-to-right row-major order:\n'''
assets=[];jobs=[];rarities=[0,0,0,1,1,1,2,2,2,3,3,4]
for seriesid,title,category,items in series:
 prompt=base+'\n'.join('Row %d, column %d: %s.'%(i//4+1,i%4+1,item[1]) for i,item in enumerate(items))
 jobs.append({'out':seriesid+'.png','prompt':prompt,'size':'1536x1024','quality':'high','background':'transparent'})
 for i,(name,desc,w,h) in enumerate(items):
  q=rarities[i];assets.append({'id':len(assets),'key':seriesid+'-'+str(i+1).zfill(2),'name':name,'series':seriesid,'seriesName':title,'category':category,'w':w,'h':h,'quality':q,'base':round((500+i*95)*[1,1.6,2.8,4.5,8][q]/10),'sheet':seriesid+'.png','cell':i,'image':f'assets/auction/items/{seriesid}-{i+1:02}.webp','description':desc})
p=Path('scripts/auction-art');(p/'catalog.json').write_text(json.dumps(assets,ensure_ascii=False,indent=2),encoding='utf8')
(p/'cel-prompts.jsonl').write_text('\n'.join(json.dumps(j,ensure_ascii=False) for j in jobs),encoding='utf8')
(p/'pilot.jsonl').write_text(json.dumps(jobs[0]),encoding='utf8')
(p/'remaining.jsonl').write_text('\n'.join(json.dumps(j) for j in jobs[1:]),encoding='utf8')
print('96 unique collectibles; 8 themed sheets; 5 rarities')
