const fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('v3test.js','utf8');
const events={};
const eventSource={events,on(n,f){(events[n]??=[]).push(f)},makeLast(n,f){(events[n]??=[]).push(f)},removeListener(){}};
const ctx={chat:[{is_user:true,mes:'old user 1'},{is_user:false,mes:'old assistant 1'},{is_user:true,mes:'old user 2'},{is_user:false,mes:'old assistant 2'},{is_user:true,mes:'latest('}],eventTypes:{GENERATE_AFTER_DATA:'GEN'},eventSource};
function X(){};X.prototype.open=function(){};X.prototype.send=function(){};
const w={parent:null,top:null,location:{href:'http://x/'},addEventListener(){},removeEventListener(){},fetch(){},XMLHttpRequest:X};w.parent=w;w.top=w;
const sb={window:w,globalThis:w,SillyTavern:{getContext:()=>ctx},console,URL,Request:function(){}};
vm.runInNewContext(code,sb);
const api=w.__inlineDynamicApiTraceNoCat__;
const input=[{role:'system',content:'HEAD',identifier:'main'},{role:'user',content:'old user 1',identifier:'chatHistory-0'},{role:'assistant',content:'old assistant 1',identifier:'chatHistory-1'},{role:'system',content:'FIXED',identifier:'rules'}];
const out=api.preview(input);
console.log('length='+out.length);
console.log('system='+out.filter(x=>x.role==='system').length);
console.log('historyIdentifiers='+out.filter(x=>String(x.identifier||'').startsWith('chatHistory')).length);
console.log('latestInAssistant='+out.some(x=>x.role==='assistant'&&String(x.content).includes('latest(')));
console.log('finalRole='+out[out.length-1].role);
console.log('finalOpen='+out[out.length-1].content.endsWith('{"role":"assistant","content":"'));
console.log(out.map(x=>({role:x.role,id:x.identifier,head:String(x.content).slice(0,70)})));
