import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFileSync,statSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve,extname,sep} from 'node:path';
import {chromium} from 'playwright';
const ROOT=resolve('.'),OUT=resolve('artifacts/auction-v32/screenshots');mkdirSync(OUT,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp','.png':'image/png','.svg':'image/svg+xml','.mp3':'audio/mpeg'};
const server=createServer((req,res)=>{try{const path=resolve(ROOT,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(!path.startsWith(ROOT+sep)||!statSync(path).isFile())throw Error();res.writeHead(200,{'Content-Type':mime[extname(path)]||'application/octet-stream'});res.end(readFileSync(path));}catch{res.writeHead(404);res.end('not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch();const report=[];
async function overflow(page,label){const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));const dialogs=await page.locator('dialog[open]').evaluateAll(ds=>ds.map(d=>({width:d.clientWidth,scroll:d.scrollWidth})));for(const d of dialogs)assert.ok(d.scroll<=d.width+1,`${label} dialog overflow ${JSON.stringify(d)}`);assert.ok(result.scroll<=result.width+1,`${label} overflow ${JSON.stringify(result)}`);}
async function shot(page,label){await page.evaluate(()=>Promise.all([...document.images].filter(i=>i.loading!=='lazy').map(i=>i.decode().catch(()=>{}))));await page.screenshot({path:resolve(OUT,label+'.png'),fullPage:true});await overflow(page,label);}
async function cabinet(page){await page.locator(page.viewportSize().width<=580?'#btnMobileCollection':'#navCollection').click();await page.waitForSelector('#collectionDialog[open]');}
try{
for(const [label,width,height] of [['desktop',1760,1000],['laptop',1280,900]]){
 const page=await browser.newPage({viewport:{width,height}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
 await page.goto(base+'/arcade/auction.html?nolimit=1');await page.evaluate(()=>localStorage.setItem('airp_arcade_wallet_v1',JSON.stringify({balance:40000})));await page.reload();
 assert.equal(await page.locator('.host-button').count(),11);await page.locator('[data-host="9"]').click();await page.waitForFunction(()=>parseFloat(getComputedStyle(document.querySelector('#hostDescription p')).fontSize)>=16);assert.equal(await page.locator('#prepare #venues').count(),0);await shot(page,label+'-prepare');
 await cabinet(page);assert.equal(await page.locator('.cabinet-card').count(),96);await shot(page,label+'-cabinet-empty');await page.locator('#collectionDialog [data-close]').click();
 await page.click('[data-open-shop]');await shot(page,label+'-shop-paged');await page.selectOption('#instrumentKind','identify');await page.click('[data-buy="identify-0"]');await page.waitForFunction(()=>AIRPAuction.getInstruments().stock['identify-0']===1);await shot(page,label+'-instrument-shop');await page.locator('#instrumentDialog [data-close]').click();await page.click('#btnStart');assert.equal(await page.locator('#admission').isVisible(),true);await shot(page,label+'-admission');await page.click('#btnConfirmEntry');await page.waitForSelector('#play:not([hidden])');assert.equal(await page.locator('.bidder').count(),4);assert.equal(await page.locator('.npc-intent').count(),0);const profiles=await page.evaluate(()=>AIRPAuction.getView().opponents);assert.equal(profiles.length,3);assert.ok(profiles.every(p=>p.host!==9&&p.tendency&&typeof p.skillUsed==='boolean'));assert.equal(await page.locator('#btnStart').isVisible(),false);assert.equal(await page.locator('#play').evaluate(e=>e.parentElement.tagName),'MAIN');await shot(page,label+'-bidding');
 await page.locator('#vault .vault-item').first().click();await page.click('#selectedCandidates');assert.ok(await page.locator('.catalog-card').count()>0);await shot(page,label+'-candidates');await page.locator('#catalogDialog [data-close]').click();await page.click('#btnFieldTools');await page.selectOption('#activeInstrument','identify-0');await page.click('#btnTool');await page.waitForFunction(()=>AIRPAuction.getView().toolUsed);assert.equal(await page.locator('#btnTool').isDisabled(),true);
 await page.click('#btnBid');await shot(page,label+'-sealed-bid');await page.click('[data-edit=clear]');for(const digit of ['5','0','00'])await page.click(`[data-digit="${digit}"]`);await page.locator('#bidForm [type=submit]').click();
 await page.waitForSelector('#resultDialog[open]',{timeout:120000});assert.equal(await page.evaluate(()=>AIRPAuction.getView().result.won),true);await shot(page,label+'-result');
 const before=await page.evaluate(()=>AIRPAuction.getBalance());await page.reload();await page.waitForSelector('#resultDialog[open]',{timeout:120000});assert.equal(await page.evaluate(()=>AIRPAuction.getBalance()),before);await page.click('#btnSkipReveal');await page.click('#btnKeep');await page.waitForSelector('#prepare:not([hidden])');
 const kept=await page.evaluate(()=>AIRPAuction.getCollection());assert.ok(kept.inventory.length>=6);assert.ok(kept.collected.length>=1);const afterKeep=await page.evaluate(()=>AIRPAuction.getBalance());assert.equal(afterKeep,before-5000);
 await cabinet(page);let pins=await page.locator('[data-pin]:not(:disabled)').count();for(let n=0;n<Math.min(6,pins);n++)await page.locator('[data-pin]:not(:disabled)').first().click();await page.locator('#collectionDialog').evaluate(e=>e.scrollTop=0);await shot(page,label+'-cabinet-filled');const pinned=await page.evaluate(()=>AIRPAuction.getCollection().pins.length);assert.ok(pinned>0);
 await page.locator('[data-sell]').first().click();await page.waitForFunction(n=>AIRPAuction.getCollection().inventory.length===n-1,kept.inventory.length);assert.equal(await page.evaluate(()=>AIRPAuction.getCollection().collected.length),kept.collected.length);const soldBalance=await page.evaluate(()=>AIRPAuction.getBalance());assert.ok(soldBalance>afterKeep);await page.reload();assert.equal(await page.evaluate(()=>AIRPAuction.getBalance()),soldBalance);assert.equal(await page.evaluate(()=>AIRPAuction.getCollection().inventory.length),kept.inventory.length-1);
 await page.click('#btnStart');await page.click('#btnConfirmEntry');await page.waitForSelector('#play:not([hidden])');await page.click('#btnPass');await page.waitForSelector('#resultDialog[open]',{timeout:120000});await page.click('#btnSkipReveal');await page.click('#btnNext');await page.waitForSelector('#prepare:not([hidden])');
 const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.currentSrc&&!i.complete||i.currentSrc&&i.naturalWidth===0).map(i=>i.src));assert.deepEqual(broken,[]);assert.deepEqual(errors,[]);report.push({label,width,height,passed:true,collected:kept.collected.length,consoleErrors:errors.length});await page.close();
}
// Hall route and wallet bridge. No-timer and landscape coverage live in check-auction-landscape.mjs.
const p=await browser.newPage({viewport:{width:1280,height:900}});await p.goto(base+'/arcade/index.html#auction');await p.waitForFunction(()=>document.querySelector('iframe')?.src.includes('auction.html'));const frame=p.frames().find(f=>f.url().includes('auction.html'));await frame.waitForSelector('#btnStart');assert.equal(await p.locator('.tab').count(),5);await shot(p,'lobby');await p.close();
writeFileSync('artifacts/auction-v32/ui-test.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();server.close();}
